//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pr22.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Box
    {
        public int NumberBox { get; set; }
        public Nullable<int> AmountSlippers { get; set; }
        public Nullable<int> IDtypeOfSlippers { get; set; }
        public Nullable<int> NumberStock { get; set; }
    
        public virtual Stock Stock { get; set; }
        public virtual TypeOfSlipper TypeOfSlipper { get; set; }
    }
}
