//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pr22.DB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SlippersProdactionEntities1 : DbContext
    {
        public SlippersProdactionEntities1()
            : base("name=SlippersProdactionEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Box> Box { get; set; }
        public virtual DbSet<Machine> Machine { get; set; }
        public virtual DbSet<Plan> Plan { get; set; }
        public virtual DbSet<Position> Position { get; set; }
        public virtual DbSet<Slipper> Slipper { get; set; }
        public virtual DbSet<Stock> Stock { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TypeOfSlipper> TypeOfSlipper { get; set; }
        public virtual DbSet<Worker> Worker { get; set; }
    }
}
