//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pr22.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Plan
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> KolvoColorsSlippers { get; set; }
        public Nullable<int> KolvoUsualySlippers { get; set; }
        public Nullable<bool> DoOrNot { get; set; }
        public Nullable<int> IDWorker { get; set; }
    
        public virtual Worker Worker { get; set; }
    }
}
