//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pr22.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Slipper
    {
        public int IDSlipper { get; set; }
        public Nullable<int> Size { get; set; }
        public Nullable<decimal> CostPrice { get; set; }
        public Nullable<int> IDTypeOfSlipper { get; set; }
        public Nullable<int> IDWorker { get; set; }
    
        public virtual TypeOfSlipper TypeOfSlipper { get; set; }
        public virtual Worker Worker { get; set; }
    }
}
